name: Cleanup github runner caches on closed pull requests
on:
  schedule:
    - cron: '17 8 * * 5'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        run: |
		  
          echo "Fetching list of cache keys"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --json id,lastAccessedAt)

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey, last_accessed_at in $cacheKeysForPR
          do
			  echo "Key: $cacheKey"
			  echo "TS: $last_accessed_at"
              ## gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge